version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin_Hermes_2024
      POSTGRES_DB: hermess
  backend:
    build: ../backend
    ports: ["8000:8000"]
    volumes: ["../ntd_base:/app/ntd_base"]
  frontend:
    build: ../frontend
    ports: ["3000:3000"]
